#!/usr/bin/env python3
"""Pillar report: composite scores for interacting criterion systems.

A pillar is a group of criteria that move together (see
docs/metric_interactions.md). Its score is the members' mean PENALIZED by
internal spread, because a system with a starved member is weaker than its
average suggests:

    adjusted = mean - penalty_factor * (max - min)

Also reports pillar trajectories across score history snapshots.

Usage:
    python tools/pillar_report.py            # console + tests/PILLARS.md
"""

import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
ANALYSIS_DIR = REPO_ROOT / "tests" / "analysis"
REPORT_PATH = REPO_ROOT / "tests" / "PILLARS.md"


def main() -> int:
    if sys.stdout.encoding and sys.stdout.encoding.lower() not in ("utf-8", "utf8"):
        sys.stdout.reconfigure(encoding="utf-8")

    pillars_doc = yaml.safe_load((ANALYSIS_DIR / "pillars.yaml").read_text(encoding="utf-8"))
    current = yaml.safe_load((ANALYSIS_DIR / "scores_current.yaml").read_text(encoding="utf-8"))
    history = yaml.safe_load((ANALYSIS_DIR / "scores_history.yaml").read_text(encoding="utf-8"))

    scores = {int(k): v for k, v in current["scores"].items()}
    penalty_factor = float(pillars_doc.get("penalty_factor", 0.25))

    out = [
        "# Pillar Report (generated)",
        "",
        "<!-- Generated by `python tools/pillar_report.py`. Do not edit by hand. -->",
        "",
        f"Revision: {current.get('meta', {}).get('revision')}   "
        f"Date: {current.get('meta', {}).get('date')}",
        "",
        "| Pillar | Members | Mean | Spread | Adjusted |",
        "|---|---|---:|---:|---:|",
    ]

    pillar_results = []
    for pillar in pillars_doc["pillars"]:
        name = pillar["name"]
        members = pillar["members"]
        values = [scores[m] for m in members if m in scores]
        if not values:
            continue
        mean = sum(values) / len(values)
        spread = max(values) - min(values)
        adjusted = mean - penalty_factor * spread
        pillar_results.append((name, members, mean, spread, adjusted))
        out.append(f"| {name} | {len(members)} | {mean:.2f} | {spread} | **{adjusted:.2f}** |")

    raw_overall = sum(scores.values()) / len(scores)
    adj_overall = sum(p[4] for p in pillar_results) / len(pillar_results)
    out += [
        "",
        f"**Raw overall:** {raw_overall:.2f}   "
        f"**System-adjusted overall:** {adj_overall:.2f}",
        "",
        "The gap between raw and adjusted overall measures hidden systemic debt:",
        "how much the averages are borrowing from starved members.",
        "",
    ]

    # Trajectories across history
    hist = history.get("history", {})
    if len(hist) >= 2:
        out += ["## Pillar trajectory", ""]
        labels = list(hist.keys())
        header = "| Pillar | " + " | ".join(labels) + " |"
        out += [header, "|---|" + "---:|" * len(labels)]
        for name, members, _, _, _ in pillar_results:
            row = [name]
            for label in labels:
                snap = {int(k): v for k, v in hist[label].get("scores", {}).items()}
                vals = [snap[m] for m in members if m in snap]
                if vals:
                    mean = sum(vals) / len(vals)
                    spread = max(vals) - min(vals)
                    row.append(f"{mean - penalty_factor * spread:.2f}")
                else:
                    row.append("—")
            out.append(" | ".join(row))
        out.append("")

        # Coupling observations: members that moved opposite directions
        out += ["## Observed couplings (between last two snapshots)", ""]
        first, second = hist[labels[0]].get("scores", {}), hist[labels[-1]].get("scores", {})
        common = sorted(set(first) & set(second), key=int)
        moved_up = [(c, second[c] - first[c]) for c in common if second[c] > first[c]]
        moved_down = [(c, second[c] - first[c]) for c in common if second[c] < first[c]]
        if moved_up or moved_down:
            out += ["| Criterion | Delta |", "|---|---:|"]
            for c, d in moved_up:
                out.append(f"| #{c} | +{d} |")
            for c, d in moved_down:
                out.append(f"| #{c} | {d} |")
            out.append("")
            out.append("_No criterion has yet been observed to fall while others rose — "
                       "the tension couplings documented in docs/metric_interactions.md "
                       "remain theoretical until a pass triggers one._")

    REPORT_PATH.write_text("\n".join(out), encoding="utf-8")
    print(f"Pillar report written to {REPORT_PATH.relative_to(REPO_ROOT)}")
    print(f"Raw overall {raw_overall:.2f}; system-adjusted overall {adj_overall:.2f}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
